services:
  nginx:
    build:
      context: /opt/docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    # depends_on:

    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16