---
- name: Setup and run Docker Compose in the background
  hosts: ubuntu_servers
  become: true
  tasks:
    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create project directory on remote host
      ansible.builtin.file:
        path: /opt/docker
        state: directory
        mode: '0755'

    - name: Copy Docker-compose.yml to remote host
      ansible.builtin.copy:
        src: ../docker/Docker-compose.yml
        dest: /opt/docker/Docker-compose.yml

    - name: Copy nginx files to remote host
      ansible.builtin.copy:
        src: ../docker/nginx/
        dest: /opt/docker/nginx/
        mode: '0755'

    - name: Copy application files to remote host
      ansible.builtin.copy:
        src: ../docker/dashboard/
        dest: /opt/docker/dashboard/
        mode: '0755'

    - name: Build and start Docker Compose in detached mode
      ansible.builtin.shell: |
        docker compose -f /opt/docker/Docker-compose.yml up -d
      args:
        chdir: /opt/docker/
