---
- name: Setup and run Docker Compose in the background
  hosts: all
  become: true
  tasks:
    - name: Ensure Docker is running
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Create project directory on remote host
      ansible.builtin.file:
        path: /opt/my_project/docker
        state: directory
        mode: '0755'

    - name: Copy Docker-compose.yml to remote host
      ansible.builtin.copy:
        src: docker/Docker-compose.yml
        dest: /opt/my_project/docker/Docker-compose.yml

    - name: Copy nginx configuration to remote host
      ansible.builtin.copy:
        src: docker/nginx/default.conf
        dest: /opt/my_project/docker/nginx/default.conf

    - name: Copy application files to remote host
      ansible.builtin.copy:
        src: docker/dashboard/
        dest: /opt/my_project/docker/dashboard/
        mode: '0755'

    - name: Build and start Docker Compose in detached mode
      ansible.builtin.shell: |
        docker compose -f /opt/my_project/docker/Docker-compose.yml up -d
      args:
        chdir: /opt/my_project/docker/
